name: Build Docker Images

on:
  push:
    tags:
      - '*'

jobs:
  build-runner:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Dotnet Restore
      run: dotnet restore ./Naami.SuiNet/
    - name: Build SuiNet
      run: dotnet build ./Naami.SuiNet/ --configuration Release -p:VersionPrefix=$RELEASE_VERSION
    - name: Pack SuiNet
      run: dotnet pack ./Naami.SuiNet/ --configuration Release -p:VersionPrefix=$RELEASE_VERSION
    - name: Publish Nuget Github Packages
      run: dotnet nuget push "./Naami.SuiNet/bin/Release/Naami.SuiNet.$RELEASE_VERSION.nupkg" --api-key ${{ secrets.DMOOS_PAT_NUGET_PUSH }} --source "github"
    - name: Publish Nuget nuget.org
      run: dotnet nuget push "./Naami.SuiNet/bin/Release/Naami.SuiNet.$RELEASE_VERSION.nupkg" --api-key ${{ secrets.DMOOS_PAT_NUGET_ORG_PUSH }} --source "nuget"